steps:
- script: mkdir package && mkdir package/build && cp -R ./build/* ./package/build && cp json-server.js ./package/json-server.js && cp db.json ./package/db.json
  displayName: 'create deploy package folder'

# Copy staticwebapp.config.json
- script: cp $(System.DefaultWorkingDirectory)/staticwebapp.config.json $(System.DefaultWorkingDirectory)/package/staticwebapp.config.json
  displayName: 'Copy staticwebapp.config.json'

# Archive build artifact
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/package'
    includeRootFolder: false
    archiveFile: '$(System.DefaultWorkingDirectory)/$(buildVersion).zip'

# Publish web build artifact (To Azure Devops)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/$(buildVersion).zip'
    artifactName: 'release-files'

# Publish api build artifact (To Azure Devops)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/package-api/api.zip'
    artifactName: 'release-files-api'